#!/usr/bin/env python3
# -*- Coding: utf-8 -*-

# 中間層可視化設定
NUMPY_VISUALIZER_WINDOW_HEIGHT = 1080
NUMPY_VISUALIZER_WINDOW_WIDTH = 1080
NUMPY_VISUALIZER_IMAGE_HEIGHT = 256
NUMPY_VISUALIZER_IMAGE_WIDTH = 256

TARGET_NUMPY_FILE = '../iot_device/data/middle_layers.npy'
